name: Deploy API

on:
  push:
    branches:
      - dev # Chạy pipeline khi có push lên nhánh dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        run: git clone https://github.com/SonNguyenne/novel-fe.git

      # Bước 2: Thiết lập Docker Buildx (bằng cách chạy lệnh trực tiếp)
      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      # Bước 3: Đăng nhập vào Docker Hub (sử dụng lệnh docker login)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Print working directory
        run: |
          pwd
          ls
      # Bước 4: Build và Push Docker image
      - name: Build and Push Docker image
        run: |
          cd novel-fe
          docker compose build app
          docker compose push app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into VPS and deploy
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /root/novel
            docker-compose down api
            docker-compose pull api
            docker-compose up -d api
          EOF
